baseURL = "https://yorsk.github.io/"
languageCode = "en-us"
title = "The Simple"
theme = "hugo-PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
